.TH snSH-color 7
.B
> ["color"] command change the actual
color of snSH logo.


also have a few flags that you can pass:

	> ["color --help"], to check the digit
number of each color.

	> ["color --define"] [digit], to define your favorite color
letter.
	digit is a number between 0-7.
Change for you personal choose.