.TH snSH 1
.B
Snail Shell or snSH, is made for study purpose.


.P
Snail Shell has a lot of built-int commands,
added for improve user experience, some of them
are simple commands passed in command line like:

	-> ["color"] this command changes the color of logo letters,
like a neo or fast fetch customizable or changes the color
of output text, for a complete overview check the oficial
man page of color command, just type:
		> man snSH-color